### ISSUE TITLE
UGT2B7 expression differs from published Dapagliflozin model

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Carbamazepine-Model#1]
UGT2B7 expression used in the carbamazepine model differs from that used in the Dapagliflozin model (https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/tree/master/Dapagliflozin).

Dapagliflozin: RT-PCR, reference concentration 3.372 µmol/l
Carbamazepine: EST, reference concentration 2.78 µmol/l

**Comment by AndreDlm** [comment]
Thanks for spotting @PavelBal

**Comment by AndreDlm** [comment]
*Note:* This issue applies only to the [carbamazepine model v1.0](https://github.com/Open-Systems-Pharmacology/Carbamazepine-Model/releases/tag/v1.0); in the [carbamazepine model v1.1](https://github.com/Open-Systems-Pharmacology/Carbamazepine-Model/releases/tag/v1.1) this has been fixed
